### ISSUE TITLE
Support for TCP socket

### ISSUE THREAD

**Issue by bsirang** [livekit/livekit-cli#66]
My use case is to feed gstreamer H264 encoded data to livekit. I saw that Unix socket support was added in https://github.com/livekit/livekit-cli/pull/25

I made a quick branch to support TCP sockets using `tcp:address` string format, similar to the existing `unix:socket_file` format.

The one thing that's missing however, is the mime type detection. For Unix sockets they are inferred based on strings in the filename. For TCP this approach is less feasible.

See my changes here: https://github.com/livekit/livekit-cli/compare/main...bsirang:livekit-cli:bsirang/sockets?expand=1

Perhaps the format can be changed to `socket_type:mime_type:address`?

**Comment by bsirang** [comment]
Here's a PR https://github.com/livekit/livekit-cli/pull/67

**Comment by dwirya** [comment]
As per my latest [comment](https://github.com/livekit/livekit-cli/pull/25#issuecomment-1193113953), it's possible to integrate gstreamer with LiveKit CLI via `stdin`. I don't think TCP streaming is a good choice here, we're introducing redundant latency from producing ACKs per packet. UDP is a slightly better choice as we don't need to do ACKs, but we'll risk having packet loss (I've seen embedded applications suffering 40-50% packet loss from UDP port forwarding). The problem with these 2 approaches is the need to packetise the payload (video, audio) in a network layer packet (in TCP, we'll need to generate TCP header). For low-latency applications such as real-time video, this can be a big burden.

The best choice in my opinion is to use Unix sockets, because it assumes that the sender and receiver are in the same host system, so we can send the payload without the TCP / UDP header. We also get lossless transfer because it's using the OS file-system. For more discussion this, see [this](https://stackoverflow.com/questions/14973942/tcp-loopback-connection-vs-unix-domain-socket-performance)
